/*
 * Copyright (C) Volker Strobel
 *
 * This file is part of paparazzi
 *
 * paparazzi is free software; you can redistribute it and/or modify
 * it under the terms of t/home/pold/paparazzi/sw/airborne/modules/computer_vision
he GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * paparazzi is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with paparazzi; see the file COPYING.  If not, see
 * <http://www.gnu.org/licenses/>.
 */

#ifndef TREXTON_SETTINGS_H
#define TREXTON_SETTINGS_H

#include <stdio.h>
#include "lib/vision/image.h"

/* Analysis */

#ifndef TREXTON_DEBUG
#define TREXTON_DEBUG false
#endif
PRINT_CONFIG_VAR(TREXTON_DEBUG)


#ifndef TREXTON_MEASURE_TIME
#define TREXTON_MEASURE_TIME false
#endif
PRINT_CONFIG_VAR(TREXTON_MEASURE_TIME)

#ifndef TREXTON_PATCH_SIZE
#define TREXTON_PATCH_SIZE  5
#endif
PRINT_CONFIG_VAR(TREXTON_PATCH_SIZE)

#ifndef TREXTON_TOTAL_PATCH_SIZE
#define TREXTON_TOTAL_PATCH_SIZE 25
#endif
PRINT_CONFIG_VAR(TREXTON_TOTAL_PATCH_SIZE)

#ifndef TREXTON_NUM_TEXTONS
#define TREXTON_NUM_TEXTONS 20
#endif
PRINT_CONFIG_VAR(TREXTON_NUM_TEXTONS)

#ifndef TREXTON_MAX_TEXTONS
#define TREXTON_MAX_TEXTONS 5000
#endif
PRINT_CONFIG_VAR(TREXTON_MAX_TEXTONS)

#ifndef TREXTON_MAX_POSSIBLE_DIST
#define TREXTON_MAX_POSSIBLE_DIST 50000
#endif
PRINT_CONFIG_VAR(TREXTON_MAX_POSSIBLE_DIST)

/* Maximum lines read from histogram CSV */
#ifndef TREXTON_NUM_HISTOGRAMS
#define TREXTON_NUM_HISTOGRAMS 445
#endif
PRINT_CONFIG_VAR(TREXTON_NUM_HISTOGRAMS)

#ifndef TREXTON_NUM_CLASSES
#define TREXTON_NUM_CLASSES 4
#endif
PRINT_CONFIG_VAR(TREXTON_NUM_CLASSES)

#ifndef TREXTON_PREDICT
#define TREXTON_PREDICT true
#endif
PRINT_CONFIG_VAR(TREXTON_PREDICT)

#ifndef TREXTON_EVALUATE
#define TREXTON_EVALUATE false
#endif
PRINT_CONFIG_VAR(TREXTON_EVALUATE)

#ifndef TREXTON_NUM_TEST_HISTOGRAMS
#define TREXTON_NUM_TEST_HISTOGRAMS 625
#endif
PRINT_CONFIG_VAR(TREXTON_NUM_TEST_HISTOGRAMS)

#ifndef TREXTON_SAVE_HISTOGRAM
#define TREXTON_SAVE_HISTOGRAM false
#endif
PRINT_CONFIG_VAR(TREXTON_SAVE_HISTOGRAM)

#ifndef TREXTON_USE_WEBCAM
#define TREXTON_USE_WEBCAM true
#endif
PRINT_CONFIG_VAR(TREXTON_USE_WEBCAM)

#ifndef TREXTON_USE_FLOW
#define TREXTON_USE_FLOW false
#endif
PRINT_CONFIG_VAR(TREXTON_USE_FLOW)

#ifndef TREXTON_HISTOGRAM_PATH
#define TREXTON_HISTOGRAM_PATH "saved.csv"
#endif
PRINT_CONFIG_VAR(TREXTON_HISTOGRAM_PATH)

#ifndef USE_CONVERSIONS
#define USE_CONVERSIONS false
#endif
PRINT_CONFIG_VAR(TREXTON_USE_CONVERSIONS)

#ifndef TREXTON_TEXTON_STANDARIZE
#define TREXTON_TEXTON_STANDARIZE true
#endif
PRINT_CONFIG_VAR(TREXTON_TEXTON_STANDARIZE)

#ifndef TREXTON_COLOR_CHANNELS
#define TREXTON_COLOR_CHANNELS 3
#endif
PRINT_CONFIG_VAR(TREXTON_COLOR_CHANNELS)

#ifndef TREXTON_NUM_COLOR_BINS
#define TREXTON_NUM_COLOR_BINS 48
#endif
PRINT_CONFIG_VAR(TREXTON_NUM_COLOR_BINS)


#ifndef TREXTON_SEND_VIDEO
#define TREXTON_SEND_VIDEO false
#endif
PRINT_CONFIG_VAR(TREXTON_SEND_VIDEO)


#ifndef TREXTON_USE_COLOR
#define TREXTON_USE_COLOR false
#endif
PRINT_CONFIG_VAR(TREXTON_USE_COLOR)

#ifndef TREXTON_USE_ALL
#define TREXTON_USE_ALL false
#endif
PRINT_CONFIG_VAR(TREXTON_USE_ALL)

#ifndef TREXTON_CHANNELS
#define TREXTON_CHANNELS 1
#endif
PRINT_CONFIG_VAR(TREXTON_CHANNELS)

#ifndef TREXTON_K
#define TREXTON_K 1
#endif
PRINT_CONFIG_VAR(TREXTON_K)

#ifndef TREXTON_USE_OPTITRACK
#define TREXTON_USE_OPTITRACK 0
#endif
PRINT_CONFIG_VAR(TREXTON_USE_OPTITRACK)

#ifndef TREXTON_SAVE_IMG_AND_HISTOGRAM
#define TREXTON_SAVE_IMG_AND_HISTOGRAM 0
#endif
PRINT_CONFIG_VAR(TREXTON_SAVE_IMG_AND_HISTOGRAM)

#ifndef TREXTON_SAVE_IMG
#define TREXTON_SAVE_IMG 0
#endif
PRINT_CONFIG_VAR(TREXTON_SAVE_IMG)

#ifndef TREXTON_VIDEO_CAPTURE_PATH
#define TREXTON_VIDEO_CAPTURE_PATH /data/video/images
#endif
PRINT_CONFIG_VAR(TREXTON_VIDEO_CAPTURE_PATH)

#if TREXTON_USE_COLOR
  #define TREXTON_SIZE_HIST TREXTON_NUM_COLOR_BINS*TREXTON_COLOR_CHANNELS
#elif TREXTON_USE_ALL
  #define TREXTON_SIZE_HIST TREXTON_NUM_TEXTONS*CHANNELS+TREXTON_NUM_COLOR_BINS*TREXTON_COLOR_CHANNELS
#else
  #define TREXTON_SIZE_HIST TREXTON_NUM_TEXTONS*TREXTON_CHANNELS
#endif


#endif
